const PACKAGES = [
    {
        title: 'Bronze plan',
        included: ['Career Guidance', 'Education counselling'],
        benefits: [
            'Clarity about Program and Institution Choice Based on Expert Advice',
            'Clarity about Career Choice',
            'Tailored Immigration Advice',
            'Clarity about Cost of Study',
            'Information about Country of Study',
        ],
    },
    {
        title: 'Silver plan',
        included: [
            'Career Guidance',
            'Counsel and Support throughout the Application Process',
            'Assistance in the Preparation/Submission of Application Documents',
            'Tuition fee payment support',
        ],
        benefits: [
            'Guaranteed Placement in Desired Institutions',
            'Offers in up to 3 Institutions',
            'Seamless Payment of Tuition Fees',
            'Clarity about Program and Institution Choice based on Expert Advice',
            'Clarity about Career Choice',
            'Tailored Immigration Advice',
            'Clarity about Cost of Study',
            'Information about Country of Study',
        ],
    },
    {
        title: 'Gold plan',
        included: [
            'Visa Support Service',
            'Education Counselling',
            'Career Guidance',
            'Counsel and Support throughout the Application Process',
            'Assistance in the Preparation/Submission of Application Documents',
            'Remittances',
            'College Admissions',
            'Airport Pickups',
            'Pastoral Care',
            'Peer Networking',
            'Mentorship',
            'Health & Travel Insurance support services',
            'Accommodation Services Support',
        ],
        benefits: [
            'Peace of Mind',
            'Guaranteed Visa',
            'Stress Free Visa Process',
            'Student Health and Travel Insurance Services',
            'Networking with current students and SL Alumni/Friends who now have successful ',
            'careers',
            'Support throughout Study Period - Liaison with School if necessary, CV support, ',
            'information about jobs, ',
            'Access to Professional Network',
            'Solid- Link Welcome Pack',
            'Seamless Transition into Host Country',
        ],
    },
];

export { PACKAGES };
